# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Louis Moreaux
subtitle: "Oracle APEX and other stuff"

email: moreaux.louis@gmail.com
description: "Simple blog about Oracle APEX"
twitter_username: moreaux_louis
github_username: LouisMoreaux
minimal_mistakes_skin: mint
search: true

repository: LouisMoreaux/fr

locale: "fr"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Paris

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Louis Moreaux"
  avatar : "/assets/images/profile-picture.jpg"
  bio    : "Développeur Oracle APEX à Paris"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/moreaux_louis"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LouisMoreaux"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/louis-moreaux/"
    - label: "Email"
      icon: "fa fa-fw fa-envelope-square"
      url: "mailto:moreaux.louis@gmail.com"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/moreaux_louis"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LouisMoreaux"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/louis-moreaux/"
    
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-B1M7QLTJKK"
    anonymize_ip: true # default

comments:
  provider: "giscus"
  giscus:
    repo_id              : "LouisMoreaux/fr"
    category_name        : "Announcements"
    category_id          : "DIC_kwDOGISEu84B_OGu"
    discussion_term      : "pathname"
    reactions_enabled    : "1"
    theme                : "light"